import { type NextPage } from "next";
import Head from "next/head";
import { api } from "~/utils/api";
const Home: NextPage = () => {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const test = api.test.test.useQuery();
  console.log("test.data", test.data);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center">hey there I am here</main>
    </>
  );
};

export default Home;
